### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by OwenNaicker** [zellerlab/GECCO#10]
![Screenshot (140)](https://user-images.githubusercontent.com/103607087/180976308-ad9c644a-0dc3-4c1b-ba50-b7558a06f10e.png)
Hi, I am trying to install GECCO on my windows laptop for a research project and keep getting this pyhmmer error.

**Comment by althonos** [comment]
Hi Owen, 

HMMER (and consequently pyHMMER) is not supported on Windows, so you won't be able to install it or GECCO natively. 

As a workaround, I think you should be able to get it to work using the Windows Subsystem for Linux 👍
