### ISSUE TITLE
[Question] What does type `NaN` mean in predictions? 

### ISSUE THREAD

**Issue by valentynbez** [zellerlab/GECCO#13]
I predicted BGC for some genomes, and I received clusters with a high probability, but the type is identified as `NaN`. How should one interpret such a result?

**Comment by althonos** [comment]
Then an empty value just means that the type classifier couldn't assign the BGC to one of the main classes from MIBiG.

The way GECCO work is by predicting first whether a region is a BGC, using a conditional random field; then, after a BGC has been predicted, it gets assigned one or more type by a random forest classifier. Meaning that a region may be labeled as a BGC but then fail to be classified as one of the existing classes. 

A BGC marked as Unknown is not necessarily *not* a BGC: if you look at MIBiG there are a bunch of BGC in the *Other* category, for those that do not fit in the Polyketide/NRP/RiPP/Saccharide/Terpene/Alkaloid types.
