### ISSUE TITLE
GECCO is not compatible with Python 3.10

### ISSUE THREAD

**Issue by apcamargo** [zellerlab/GECCO#7]
GECCO can't be installed in a Python 3.10 environment. This is actually caused because [`python-crfsuite` won't build in Python 3.10](https://github.com/scrapinghub/python-crfsuite/issues/130), so I'm not really sure if there's an option other than waiting for an upstream fix or changing the CRF backend.

**Comment by althonos** [comment]
Hi Antonio, as you pointed out this is a bug with `python-crfsuite` so at the moment there's not much we can do about it until they publish a fix. You can however get a working version by installing directly from the `master` branch of `python-crfsuite`, which has been fixed:
```console
$ pip install -U git+https://github.com/scrapinghub/python-crfsuite.git
```

**Comment by apcamargo** [comment]
Apparently this is not a problem anymore :)

**Comment by althonos** [comment]
Perfect ! :smile:
