### ISSUE TITLE
do not run pyrodigal if input is genbank

### ISSUE THREAD

**Issue by xvazquezc** [zellerlab/GECCO#8]
Hi,
I ran GECCO v0.9.2 with default settings (`gecco run --antismash-sedeload` with genbank input) and it went smoothly. However, there was an issue when I tried to incorporate the annotations into antiSMASH:
```
ERROR    02/05 14:39:56   sideloaded area contains no complete CDS features in cfod1: Subregion(GECCO, 209296-212824, Unknown)
```
I thought it could be an issue with the parsing of the data into the sideloader, but the problem was that the genome, already gene-called in GenBank format, had been re-processed, and so, the coordinates of the genes and CDS didn't match any more (the input was a fungal genome). I don't know if this is an intended behaviour but it does break compatibility with the user's possible extant annotations and/or with database-sourced genomes. It also removes the possibility of predicting eukaryotic genomes, and probably a bit of a waste redoing the gene-calling if this has already been provided.

Regards

**Comment by althonos** [comment]
Hi @xvazquezc 

At the moment GECCO will always redo the gene calling because we were mostly processing metagenomes, so I didn't implement this. I will add support for CDS annotations from GenBank when I get the time.

**Comment by althonos** [comment]
Hi @xvazquezc 

I made a new release (`v0.9.4`) which implements reading the genes from a GenBank input. You need to enable it with a CLI flag to instruct GECCO to use the features, e.g.:
```python
gecco run -g genome.gbk --cds-feature CDS
```
if your genes are labeled with CDS features in `genome.gbk`.
